export const aliens = {
	// PURPLE PSYKICKS - The main alien race (da-we)
	psykick_scout: {
		name: 'Psykick Scout',
		spriteIndex: 0,
		health: 25,
		behavior: {
			type: 'curious',
			movement: 'approach',
			aggressionLevel: 'low',
			detectionRange: 4,
			interestDuration: [3, 6],
			messageFrequency: 40,
		},
		messages: [
			'*observes your drilling with patient wisdom* You dig well, small miner, but do you understand what you uncover?',
			'*telepathic teaching-harmonics* The deep-ore holds more than metal, it remembers the great-pattern',
			'Each strike of your drill serves the spiral, though you know it not, tunnel-maker',
			'*sends visions of crystalline mathematics* Your fuel burns bright, but the Belt burns eternal',
			'The scattered-treasures call to each other across the void, you help them sing',
			'*chittering that carries ancient knowledge* Your rig seeks the surface, but wisdom flows deeper',
			'Small miner learns the four elements through necessity: fuel, metal, fire, void',
			'*telepathic whispers of cosmic law* What falls apart gathers again, the Belt teaches this truth',
			'You think you mine for credits, but serve a larger accounting, little seeker',
		],
		description:
			'A small, purple-hued alien that observes miners with intelligent curiosity. Seems to communicate telepathically.',
	},

	psykick_warrior: {
		name: 'Psykick Warrior',
		spriteIndex: 3,
		health: 45,
		behavior: {
			type: 'melee',
			movement: 'aggressive',
			damage: 15,
			aggressionLevel: 'high',
			detectionRange: 6,
			pursuitEnergy: [3, 8],
			attackCooldown: 1500,
			messageFrequency: 0,
		},
		description: 'Aggressive alien defender with crystalline protrusions. Attacks intruders near sacred sites.',
	},

	// ORANGE/RED ROCK DWELLERS - Native asteroid creatures
	rock_mite: {
		name: 'Rock Mite',
		spriteIndex: 6,
		health: 15,
		behavior: {
			type: 'curious',
			movement: 'cautious',
			aggressionLevel: 'low',
			detectionRange: 3,
			interestDuration: [2, 4],
			messageFrequency: 60,
		},
		messages: [
			'*tiny clicking morse-code: curiosity curiosity curiosity*',
			'*scuttles in perfect geometric patterns around your drill-marks*',
			'*collects the dust-fragments you leave behind with reverent care*',
			'*watches with compound eyes that reflect star-mathematics*',
			'*skitters in spirals that trace the golden ratio*',
			'*makes crystalline chiming sounds when you find pure minerals*',
			'*follows your tunnel-paths like they reveal sacred geometry*',
			'*clicks in rhythms that match your heartbeat when you pause*',
			'*arranges tiny rock-fragments into perfect compass-rose patterns*',
		],
		description:
			'Small indigenous creatures that live in asteroid crevices. Harmless but curious about mining operations.',
	},

	tunnel_chomper: {
		name: 'Tunnel Chomper',
		spriteIndex: 9,
		health: 35,
		behavior: {
			type: 'melee',
			movement: 'territorial',
			damage: 12,
			aggressionLevel: 'medium',
			detectionRange: 4,
			pursuitEnergy: [2, 5],
			attackCooldown: 1200,
			messageFrequency: 0,
		},
		description: 'Aggressive rock-boring creature with powerful mandibles. Territorial about tunnel systems.',
	},

	lava_spitter: {
		name: 'Lava Spitter',
		spriteIndex: 12,
		health: 30,
		behavior: {
			type: 'spawn',
			movement: 'defensive',
			aggressionLevel: 'medium',
			detectionRange: 5,
			spawnConfig: {
				spawnChance: 25,
				spawnType: 'hazard',
				spawnRadius: 1,
				spawn: 'lava',
				cooldown: [3, 8],
			},
			messageFrequency: 0,
		},
		description: 'Volcanic creature that creates lava pools when threatened. Avoid at all costs.',
	},

	// BLUE/TEAL DEEP DWELLERS - Deep asteroid creatures
	void_drifter: {
		name: 'Void Drifter',
		spriteIndex: 15,
		health: 20,
		behavior: {
			type: 'scared',
			movement: 'flee',
			aggressionLevel: 'none',
			detectionRange: 5,
			flightResponse: 'immediate',
			panicThreshold: 2,
			messageFrequency: 30,
		},
		messages: [
			'*phases through dimensions as you approach* Your solid-thinking disturbs the between-spaces',
			'*emits frequency-patterns that show alternate mining-paths* Many tunnels exist in parallel',
			'*flickers between realities* In one dimension you succeed, in another you transform',
			'*exists at the edge of perception* The void teaches patience to those who drill too fast',
			'*haunts the deep-tunnels with dimensional wisdom* Some passages lead to elsewhere',
			'*whispers from between worlds* Your drill reaches through more than stone',
			'*phases in and out like cosmic breathing* The Belt exists in all realities simultaneously',
			'*projects astral-shadows of your future mining-paths* Choose with dimensional awareness',
			'*resonates at frequencies that bypass normal space* Distance is illusion, depth is truth',
		],
		description:
			'Ethereal deep-space entity that phases in and out of reality. Flees from bright lights and loud noises.',
	},

	depth_guardian: {
		name: 'Depth Guardian',
		spriteIndex: 18,
		health: 55,
		behavior: {
			type: 'melee',
			movement: 'guardian',
			damage: 18,
			aggressionLevel: 'high',
			detectionRange: 8,
			pursuitEnergy: [5, 12],
			attackCooldown: 1000,
			messageFrequency: 0,
		},
		description: 'Ancient protector of deep asteroid cores. Becomes aggressive when miners dig too deep.',
	},

	// GREEN HIVE CREATURES - Swarm types
	hive_drone: {
		name: 'Hive Drone',
		spriteIndex: 21,
		health: 12,
		behavior: {
			type: 'neutral',
			movement: 'wander',
			aggressionLevel: 'none',
			detectionRange: 3,
			wanderPattern: 'systematic',
			wanderMoves: [1, 3],
			messageFrequency: 15,
		},
		messages: [
			'*transmits your mining-patterns to the collective-mind* This one digs with purpose',
			'*harmonizes with your drill-frequency* The hive learns from your tunnel-wisdom',
			'*shares your fuel-efficiency data across hive-channels* All benefit from one-miner learning',
			'*vibrates approval when you discover pure minerals* The collective celebrates small-victories',
			'*broadcasts your position to hive-siblings* Safety-in-numbers for all who tunnel',
			'*hums mining-rhythms that optimize your drilling-efficiency* Hive-knowledge freely shared',
			'*processes your cargo-weight calculations through collective-intelligence* Maximum efficiency achieved',
			'*synchronizes breathing-patterns with your life-support systems* Shared-survival wisdom',
			'*integrates your path-finding into hive-navigation database* All tunnels mapped, all miners guided',
		],
		description: 'Worker creature from a hive mind. Usually peaceful unless the hive is threatened.',
	},

	hive_soldier: {
		name: 'Hive Soldier',
		spriteIndex: 24,
		health: 40,
		behavior: {
			type: 'melee',
			movement: 'coordinated',
			damage: 14,
			aggressionLevel: 'medium',
			detectionRange: 5,
			pursuitEnergy: [4, 8],
			attackCooldown: 1100,
			messageFrequency: 0,
		},
		description: 'Aggressive defender of hive territory. Attacks in coordinated groups.',
	},

	gas_sporecyst: {
		name: 'Gas Sporecyst',
		spriteIndex: 27,
		health: 25,
		behavior: {
			type: 'spawn',
			movement: 'defensive',
			aggressionLevel: 'medium',
			detectionRange: 4,
			spawnConfig: {
				spawnChance: 30,
				spawnType: 'hazard',
				spawnRadius: 1,
				spawn: 'gas',
				cooldown: [2, 6],
			},
			messageFrequency: 0,
		},
		description: 'Biological gas generator that releases toxic clouds when disturbed.',
	},

	// SPECIALIZED CREATURES
	mimic_ore: {
		name: 'Mimic Ore',
		spriteIndex: 30,
		health: 30,
		behavior: {
			type: 'ambush',
			movement: 'stationary_until_triggered',
			damage: 20,
			aggressionLevel: 'high',
			detectionRange: 1,
			ambushRadius: 1,
			surpriseAttack: true,
			messageFrequency: 0,
		},
		description: 'Cunning predator that disguises itself as valuable minerals. Ambushes unsuspecting miners.',
	},

	spawn_mother: {
		name: 'Spawn Mother',
		spriteIndex: 33,
		health: 60,
		behavior: {
			type: 'spawn',
			movement: 'stationary',
			aggressionLevel: 'low',
			detectionRange: 6,
			spawnConfig: {
				spawnChance: 15,
				spawnType: 'alien',
				spawnRadius: 2,
				spawn: { rock_mite: 60, hive_drone: 40 },
				cooldown: [5, 10],
				maxSpawns: 3,
			},
			messageFrequency: 0,
		},
		description: 'Large breeding creature that spawns smaller aliens when threatened.',
	},

	// NEW NON-COMBATIVE SPAWN ALIENS
	gift_bearer: {
		name: 'Gift Bearer',
		spriteIndex: 21,
		health: 20,
		behavior: {
			type: 'spawn',
			movement: 'curious',
			aggressionLevel: 'none',
			detectionRange: 4,
			spawnConfig: {
				spawnChance: 10,
				spawnType: 'item',
				spawnRadius: 0,
				spawn: { oil: 40, repair_nanites: 30, battery: 20, spaceco_teleporter: 10 },
				cooldown: [8, 15],
			},
			messageFrequency: 70,
		},
		messages: [
			"*offers gifts with gentle chittering* The generous miner receives the Belt's abundance",
			'*drops precious items with ceremonial care* What flows freely returns as blessing',
			'*bestows tools upon the patient digger* Wisdom recognizes wisdom in all forms',
			'*presents fuel to the struggling rig* The Belt provides for those who serve',
			'*makes gift-sounds that carry ancient approval* Open hands receive sky-treasures',
			'*offers equipment with reverent clicking* True miners earn the deepest rewards',
			'*drops supplies while humming cosmic harmonies* Generosity teaches the spiral-law',
			'*bestows rare items upon the worthy* The Belt honors those who dig with purpose',
			'*chitters the universal truth* What you give to the void, the void returns transformed',
		],
		description: 'Peaceful creature that occasionally offers gifts to miners as tribute.',
	},

	earth_mover: {
		name: 'Earth Mover',
		spriteIndex: 9,
		health: 35,
		behavior: {
			type: 'spawn',
			movement: 'wander',
			aggressionLevel: 'none',
			detectionRange: 3,
			spawnConfig: {
				spawnChance: 20,
				spawnType: 'ground',
				spawnRadius: 1,
				spawn: { white: 50, orange: 30, yellow: 20 },
				cooldown: [4, 8],
			},
			messageFrequency: 25,
		},
		messages: [
			'*rumbles with the patience of geological time* Every tunnel-scar will heal in the turning',
			'*fills blast-holes with methodical devotion* What miners break, the Belt remembers how to mend',
			'*grinds stone into place with cosmic persistence* Destruction and creation dance the same spiral',
			'*works tirelessly to restore tunnel-balance* The wounded asteroid learns wholeness through time',
			'*builds new rock-formations with earth-song humming* All scars become doorways to deeper wisdom',
			'*repairs mining-damage with reverential care* The Belt forgives all who learn to give back',
			'*reshapes broken passages into sacred geometry* Even chaos serves the pattern when love guides',
			'*fills craters while teaching stone-patience* What seems ruined prepares for transformation',
			'*moves earth with the rhythm of planetary breathing* The great-mending never ends, never begins',
		],
		description: 'Industrious creature that repairs damage to asteroid structure by filling holes.',
	},

	resource_seeker: {
		name: 'Resource Seeker',
		spriteIndex: 15,
		health: 25,
		behavior: {
			type: 'spawn',
			movement: 'scared',
			aggressionLevel: 'none',
			detectionRange: 5,
			flightResponse: 'gradual',
			panicThreshold: 3,
			spawnConfig: {
				spawnChance: 8,
				spawnType: 'item',
				spawnRadius: 1,
				spawn: {
					super_oxygen_liquid_nitrogen: 30,
					battery: 25,
					advanced_teleporter: 20,
					gravity_charge: 15,
					void_implosion: 10,
				},
				cooldown: [10, 20],
			},
			messageFrequency: 20,
		},
		messages: [
			'*hoards rare fuel in dimensional pockets* The desperate miner grasps, the wise miner receives',
			'*phases equipment between realities when startled* Panic scatters treasures, calm gathers them',
			'*drops advanced tools accidentally* What you chase through the void flees into darkness',
			'*makes soft chiming when approached slowly* Patient miners discover the deepest supply caches',
			'*reluctantly shares dimensional storage when treated gently* Fear hoards, trust multiplies abundance',
			'*accidentally reveals hidden equipment stashes* The Belt rewards those who seek without desperation',
			'*provides rare resources to steady hands* Frantic digging finds rocks, calm digging finds treasures',
			'*chimes the teaching-frequency* True wealth appears in the pause between wanting and taking',
			'*shares cosmic storage-wisdom* Even scattered resources remember their gathering-pattern',
		],
		description: 'Elusive creature that hoards valuable resources and occasionally drops them when startled.',
	},

	// MYSTERY SPAWNER - The bottom sprite
	mystery_spawner: {
		name: 'Unknown Entity',
		spriteIndex: 36,
		health: 1,
		behavior: {
			type: 'spawn',
			movement: 'stationary',
			aggressionLevel: 'unknown',
			detectionRange: 3,
			spawnConfig: {
				spawnChance: 35,
				spawnType: 'alien',
				spawnRadius: 1,
				spawn: 'psykick_scout',
				cooldown: [1, 3],
			},
			messageFrequency: 0,
		},
		description: 'Unidentified alien structure. Purpose unknown. Approach with extreme caution.',
	},

	// ELITE VARIANTS (higher damage, better rewards)
	elite_psykick_warrior: {
		name: 'Elite Psykick Warrior',
		spriteIndex: 3,
		health: 65,
		behavior: {
			type: 'melee',
			movement: 'aggressive',
			damage: 22,
			aggressionLevel: 'very_high',
			detectionRange: 8,
			pursuitEnergy: [6, 12],
			attackCooldown: 1200,
			messageFrequency: 0,
		},
		description: 'Veteran alien defender with enhanced crystalline armor. Extremely aggressive near sacred sites.',
	},

	ancient_depth_guardian: {
		name: 'Ancient Depth Guardian',
		spriteIndex: 18,
		health: 80,
		behavior: {
			type: 'melee',
			movement: 'guardian',
			damage: 25,
			aggressionLevel: 'very_high',
			detectionRange: 10,
			pursuitEnergy: [8, 15],
			attackCooldown: 800,
			messageFrequency: 0,
		},
		description: 'Millennia-old protector of the deepest asteroid cores. Attacks with primordial fury.',
	},

	alpha_tunnel_chomper: {
		name: 'Alpha Tunnel Chomper',
		spriteIndex: 9,
		health: 50,
		behavior: {
			type: 'melee',
			movement: 'territorial',
			damage: 18,
			aggressionLevel: 'high',
			detectionRange: 6,
			pursuitEnergy: [4, 8],
			attackCooldown: 1000,
			messageFrequency: 0,
		},
		description: 'Pack leader with oversized mandibles. Coordinates attacks with nearby chompers.',
	},

	volatile_lava_spitter: {
		name: 'Volatile Lava Spitter',
		spriteIndex: 12,
		health: 45,
		behavior: {
			type: 'spawn',
			movement: 'defensive',
			aggressionLevel: 'high',
			detectionRange: 6,
			spawnConfig: {
				spawnChance: 35,
				spawnType: 'hazard',
				spawnRadius: 3,
				spawn: 'lava',
				cooldown: [2, 6],
			},
			messageFrequency: 0,
		},
		description: 'Unstable volcanic creature that creates extensive lava fields when threatened.',
	},

	enhanced_gas_sporecyst: {
		name: 'Enhanced Gas Sporecyst',
		spriteIndex: 27,
		health: 40,
		behavior: {
			type: 'spawn',
			movement: 'curious',
			aggressionLevel: 'medium',
			detectionRange: 5,
			spawnConfig: {
				spawnChance: 40,
				spawnType: 'hazard',
				spawnRadius: 2,
				spawn: 'gas',
				cooldown: [1, 4],
			},
			messageFrequency: 0,
		},
		description: 'Evolved sporecyst that produces more potent and widespread gas clouds.',
	},

	grand_spawn_mother: {
		name: 'Grand Spawn Mother',
		spriteIndex: 33,
		health: 90,
		behavior: {
			type: 'spawn',
			movement: 'stationary',
			aggressionLevel: 'medium',
			detectionRange: 8,
			spawnConfig: {
				spawnChance: 25,
				spawnType: 'alien',
				spawnRadius: 3,
				spawn: {
					rock_mite: 30,
					hive_drone: 25,
					hive_soldier: 20,
					tunnel_chomper: 15,
					gas_sporecyst: 10,
				},
				cooldown: [3, 8],
				maxSpawns: 5,
			},
			messageFrequency: 0,
		},
		description: 'Ancient matriarch that spawns multiple alien types across wide areas.',
	},

	master_gift_bearer: {
		name: 'Master Gift Bearer',
		spriteIndex: 21,
		health: 35,
		behavior: {
			type: 'spawn',
			movement: 'curious',
			aggressionLevel: 'none',
			detectionRange: 5,
			spawnConfig: {
				spawnChance: 15,
				spawnType: 'item',
				spawnRadius: 1,
				spawn: {
					super_oxygen_liquid_nitrogen: 25,
					advanced_teleporter: 20,
					gravity_charge: 20,
					void_implosion: 15,
					repair_nanites: 10,
					spaceco_teleport_station: 10,
				},
				cooldown: [5, 12],
			},
			messageFrequency: 80,
		},
		messages: [
			'*ancient ceremonial humming accompanies each gift* The deep-digger has earned what the Belt offers',
			'*bestows treasures with elder wisdom* Your patience in the tunnels teaches the cosmic law',
			'*presents offerings with the weight of millennia* What you give to your digging, returns transformed',
			"*drops gifts that carry approval of the watching stars* True miners receive the Belt's deepest blessing",
			'*offers equipment with reverent clicking* The spiral-law provides for those who serve the pattern',
			'*makes gift-giving sounds that echo through dimensions* Generous miners open doors to abundance',
			'*bestows rare supplies with cosmic ceremony* The Belt remembers every act of mining-devotion',
			'*emanates ancient approval-harmonies* Elder-gifts flow to those who dig with sacred purpose',
			'*presents treasures while teaching the universal truth* What serves the whole, returns as providence',
		],
		description: 'Elder gift-bearer that offers rare and valuable items to worthy miners.',
	},
};
