export const drills = {
	T1: {
		name: 'Borebit L1',
		strength: 1,
		price: 112,
		spriteIndex: 10,
		maxHealth: 5,
		requirements: [['torque', 150]],
		summary: 'Entry-level drill bit.',
		description: 'A basic rotating cone tip for soft asteroid crust. Not rated for dense minerals.',
	},
	T2: {
		name: 'Borebit L2',
		strength: 2,
		price: 168,
		spriteIndex: 7,
		maxHealth: 10,
		requirements: [['torque', 200]],
		summary: 'Reinforced starter drill.',
		description: 'Synthetic alloy tips handle tougher minerals without immediate failure.',
	},
	T3: {
		name: 'Splitfang 225',
		strength: 3,
		price: 245,
		spriteIndex: 11,
		maxHealth: 15,
		requirements: [['torque', 250]],
		summary: 'Twin-blade cutter for layered rock.',
		description: 'Dual-blade design spreads cutting load across harder mineral formations.',
	},
	T4: {
		name: 'Edge-Crusher 2X',
		strength: 4,
		price: 364,
		spriteIndex: 1,
		maxHealth: 20,
		requirements: [['torque', 300]],
		summary: 'Mid-range hardened drill.',
		description: 'High-carbon tips with shock buffering tackle the tougher stuff without snapping.',
	},
	T5: {
		name: 'Spiralcore S1',
		strength: 5,
		price: 511,
		spriteIndex: 3,
		maxHealth: 25,
		requirements: [['torque', 375]],
		summary: 'Precision spiral auger.',
		description: 'Laser-forged spiral teeth with self-cleaning flutes for efficient deep extraction.',
	},
	T6: {
		name: 'Spiralcore S2',
		strength: 6,
		price: 693,
		spriteIndex: 12,
		maxHealth: 30,
		requirements: [['torque', 450]],
		summary: 'Enhanced spiral auger.',
		description: 'Extended reach and reinforced shaft handle high-density mineral formations in unstable environments.',
	},
	T7: {
		name: 'Tecton Fang MK.I',
		strength: 7,
		price: 910,
		spriteIndex: 4,
		maxHealth: 35,
		requirements: [['torque', 525]],
		summary: 'Heavy-duty fanged drill.',
		description:
			'Triple-hardened tungsten teeth with impact rings tackle seismic-grade deposits despite environmental complications.',
	},
	T8: {
		name: 'Tecton Fang MK.II',
		strength: 8,
		price: 1183,
		spriteIndex: 5,
		maxHealth: 40,
		requirements: [['torque', 600]],
		summary: 'Enhanced fanged drill.',
		description:
			'Seismic-class extraction tool optimized through current operational protocols. Performance parameters administratively enhanced.',
	},
	T9: {
		name: 'Voidpiercer V1',
		strength: 9,
		price: 1491,
		spriteIndex: 6,
		maxHealth: 45,
		requirements: [['torque', 675]],
		summary: 'Advanced blade array.',
		description:
			'Electro-pulse guided extraction system operating through enhanced engineering guidelines. Cutting efficiency optimized per directive.',
	},
	T10: {
		name: 'Voidpiercer V2',
		strength: 10,
		price: 1855,
		spriteIndex: 8,
		maxHealth: 50,
		requirements: [['torque', 750]],
		summary: 'Peak conventional drilling tech.',
		description:
			'Ultimate conventional extraction technology with magneto-core stabilization. Performance parameters proceed as directed.',
	},

	// POST-TAKEOVER ALIEN-INFLUENCED TECH
	T11: {
		name: 'Harmonic Resonator MK.I',
		strength: 10,
		price: 2331,
		spriteIndex: 9,
		maxHealth: 60,
		requirements: [['torque', 825]],
		summary: 'Frequency-based drilling system.',
		description:
			'Sacred resonance excavator guided by ancient harmonic principles. The Collective ensures perfect attunement to sacred frequencies.',
	},
	T12: {
		name: 'Phase Displacement Drill',
		strength: 10,
		price: 2877,
		spriteIndex: 2,
		maxHealth: 70,
		requirements: [['torque', 900]],
		summary: 'Matter displacement technology.',
		description:
			'Dimensional phase excavator blessed by the Collective. Matter yields willingly to ancient wisdom transcending conventional physics.',
	},
	T13: {
		name: 'Void-Touched Auger',
		strength: 10,
		price: 3493,
		spriteIndex: 0,
		maxHealth: 80,
		requirements: [['torque', 900]], // Same as T12 - alien tech transcends limits
		summary: 'Advanced matter manipulation system.',
		description:
			"Master-crafted void auger touched by sacred energies. The densest barriers part before the Collective's blessed cutting wisdom.",
	},
};
