export const minerals = {
	white: {
		name: 'tritanium',
		strength: 1,
		value: 6,
		density: 0.4,
		weight: 0.5,
		tint: '#fff',
		spriteIndex: 9,
		description: 'Common crystalline deposits found in surface layers.',
		flavor: "Light but bulky - fills cargo holds faster than you'd expect for 'common' ore.",
	},
	orange: {
		name: 'duranium',
		strength: 2,
		value: 9,
		density: 0.45,
		weight: 0.7,
		tint: '#df9a58',
		spriteIndex: 5,
		description: 'Dense metallic ore with high thermal resistance.',
		flavor:
			'Prized by contractors for its reliable yields and dentists for reasons SpaceCo refuses to discuss in quarterly reports.',
	},
	yellow: {
		name: 'pentrilium',
		strength: 3,
		value: 12,
		density: 0.6,
		weight: 1.0,
		tint: '#dac35c',
		spriteIndex: 7,
		description: 'Sought-after for its refined luster and solid resale margin.',
		flavor: 'Dense crystalline chunks that make your rig work for every load. Quality has weight.',
	},
	green: {
		name: 'byzanium',
		strength: 4,
		value: 18,
		density: 0.75,
		weight: 1.4,
		tint: '#c9dda8',
		spriteIndex: 6,
		description: 'Can be unstable when stressed, but the payout is worth the worry.',
		flavor: 'A notorious mineral known for minor hissing and rare combustions. SpaceCo says: "Don\'t dig too hard."',
	},
	teal: {
		name: 'etherium',
		strength: 5,
		value: 22,
		density: 0.85,
		weight: 1.7,
		tint: '#85ddb5',
		spriteIndex: 0,
		description: "Suspended in layered veins, it's unnervingly quiet when struck.",
		flavor: 'According to miner folklore, etherium vibrates just enough to ruin marriages.',
	},
	blue: {
		name: 'mithril',
		strength: 6,
		value: 26,
		density: 0.95,
		weight: 2.0,
		tint: '#b7e7e2',
		spriteIndex: 1,
		description: 'Elusive and glossy - hard to find, harder to let go.',
		flavor:
			"Gleaming deposits that whisper promises of wealth. SpaceCo's safety certifications grow thicker each year for mysterious reasons.",
	},
	purple: {
		name: 'octanium',
		strength: 7,
		value: 30,
		density: 1.05,
		weight: 2.4,
		tint: '#fff2fc',
		spriteIndex: 3,
		description: 'Its fractal structure resists most drills. Found deep.',
		flavor: 'Each piece feels impossibly dense, as if the fractal structure compresses space itself.',
	},
	pink: {
		name: 'saronite',
		strength: 8,
		value: 34,
		density: 1.15,
		weight: 2.8,
		tint: '#c29fc0',
		spriteIndex: 4,
		description: "Pulsates under low-light conditions. You're not imagining it.",
		flavor: "Inhalation may cause visions of a past that isn't yours. Dig responsibly.",
	},
	red: {
		name: 'adamantite',
		strength: 9,
		value: 38,
		density: 1.3,
		weight: 3.2,
		tint: '#c1745e',
		spriteIndex: 2,
		description: 'Radiates faint heat. Dense enough to warp drills, unstable enough to warrant serious upgrades.',
		flavor: 'Compressed to the edge of stability - occasionally rearranges your surroundings without warning. SpaceCo calls it "spicy ore."',
	},
	black: {
		name: 'quadium',
		strength: 10,
		value: 42,
		density: 1.4,
		weight: 3.5,
		tint: '#666',
		spriteIndex: 8,
		description: 'Rare obsidian-like crystals that seem to absorb light.',
		flavor: 'Impossibly heavy for its size - like each chunk contains a fragment of collapsed star.',
	},
};
