export const vehicles = {
	T1: {
		name: 'SCRY-01 "Rookie"',
		price: 273,
		spriteIndex: 0,
		maxHealth: 10,
		maxFuel: 25,
		maxCargo: 20,
		maxItemSlots: 6,
		fuelEfficiency: 1,
		summary: 'Entry-level mining rig with minimal capacity.',
		description: 'Compact starter rig built from repurposed survey equipment. Light, cheap, and gets you underground.',
	},
	T2: {
		name: 'MKII-15 "Groundhog"',
		price: 441,
		spriteIndex: 9,
		maxHealth: 15,
		maxFuel: 30,
		maxCargo: 30,
		maxItemSlots: 6,
		fuelEfficiency: 1,
		summary: 'Improved storage and basic durability.',
		description:
			'Popular among freelance miners. Dual cargo bays and reinforced frame handle early operations reliably.',
	},
	T3: {
		name: 'BRNX-42 "Tunneler"',
		price: 658,
		spriteIndex: 11,
		maxHealth: 20,
		maxFuel: 35,
		maxCargo: 60,
		maxItemSlots: 8,
		fuelEfficiency: 1,
		summary: 'Built for sustained underground work.',
		description:
			'Heavier construction and expanded fuel capacity let you stay in the dig longer without surface trips.',
	},
	T4: {
		name: 'CORE-88 "Prospector"',
		price: 945,
		spriteIndex: 1,
		maxHealth: 25,
		maxFuel: 45,
		maxCargo: 90,
		maxItemSlots: 8,
		fuelEfficiency: 1,
		summary: 'Balanced mid-tier mining platform.',
		description:
			'Field-tested design favored by professional survey teams. Reliable performance in challenging conditions.',
	},
	T5: {
		name: 'HAUL-31 "Packmule"',
		price: 1344,
		spriteIndex: 6,
		maxHealth: 30,
		maxFuel: 50,
		maxCargo: 120,
		maxItemSlots: 10,
		fuelEfficiency: 2,
		summary: 'Heavy cargo specialist.',
		description: 'Industrial-grade hauler designed for maximum payload capacity. Slow but incredibly productive.',
	},
	T6: {
		name: 'STORM-50 "Ranger"',
		price: 1855,
		spriteIndex: 2,
		maxHealth: 35,
		maxFuel: 65,
		maxCargo: 130,
		maxItemSlots: 10,
		fuelEfficiency: 2,
		summary: 'Long-range exploration rig.',
		description:
			'Extended fuel capacity and environmental shielding make this ideal for deep belt operations with highly irregular conditions.',
	},
	T7: {
		name: 'BELT-70 "Pathfinder"',
		price: 2478,
		spriteIndex: 4,
		maxHealth: 40,
		maxFuel: 75,
		maxCargo: 150,
		maxItemSlots: 12,
		fuelEfficiency: 2,
		summary: 'Advanced belt navigation platform.',
		description:
			'Designed for extended missions across multiple asteroid systems. Enhanced protocols for dangerous environmental anomalies.',
	},
	T8: {
		name: 'CORE-85 "Vaultbreaker"',
		price: 3241,
		spriteIndex: 7,
		maxHealth: 45,
		maxFuel: 90,
		maxCargo: 160,
		maxItemSlots: 12,
		fuelEfficiency: 3,
		summary: 'Deep core excavation specialist.',
		description:
			'Reinforced platform rated for extreme pressure environments. All specifications have been updated per current operational requirements.',
	},
	T9: {
		name: 'TITAN-90 "Fortress"',
		price: 4151,
		spriteIndex: 12,
		maxHealth: 50,
		maxFuel: 100,
		maxCargo: 180,
		maxItemSlots: 14,
		fuelEfficiency: 3,
		summary: 'Heavy-duty endurance platform.',
		description:
			'Maximum survivability and payload capacity. Construction parameters optimized through enhanced engineering protocols.',
	},
	T10: {
		name: 'APEX-13 "Sovereign"',
		price: 5243,
		spriteIndex: 10,
		maxHealth: 55,
		maxFuel: 115,
		maxCargo: 200,
		maxItemSlots: 14,
		fuelEfficiency: 3,
		summary: 'Elite deep-space mining rig.',
		description:
			'Peak extraction platform representing conventional mining technology. Performance optimized through current administrative guidelines.',
	},
	T11: {
		name: 'VOID-88 "Leviathan"',
		price: 6552,
		spriteIndex: 8,
		maxHealth: 60,
		maxFuel: 125,
		maxCargo: 240,
		maxItemSlots: 16,
		fuelEfficiency: 4,
		summary: 'Massive cargo capacity specialist.',
		description:
			'Enhanced logistics platform incorporating new engineering principles. Specifications exceed theoretical performance models through harmonic optimization.',
	},
	T12: {
		name: 'QUANTUM-09 "Starjumper"',
		price: 8078,
		spriteIndex: 5,
		maxHealth: 65,
		maxFuel: 140,
		maxCargo: 260,
		maxItemSlots: 16,
		fuelEfficiency: 4,
		summary: 'Advanced fuel-efficient design.',
		description:
			'Efficiency platform utilizing unconventional physics principles. Fuel consumption patterns blessed by sacred harmonic resonance.',
	},
	T13: {
		name: 'NEXUS-77 "Voidwalker"',
		price: 9863,
		spriteIndex: 13,
		maxHealth: 70,
		maxFuel: 150,
		maxCargo: 300,
		maxItemSlots: 18,
		fuelEfficiency: 4,
		summary: 'High-performance hybrid platform.',
		description:
			'Sacred technology platform channeling void-touched engineering wisdom. Multi-system performance transcends conventional limitations.',
	},
	T14: {
		name: 'TRANSCEND-99 "Voidmaster"',
		price: 11942,
		spriteIndex: 3,
		maxHealth: 75,
		maxFuel: 170,
		maxCargo: 350,
		maxItemSlots: 18,
		fuelEfficiency: 5,
		summary: 'Ultimate mining platform.',
		description:
			"Master-crafted transcendent vessel embodying perfect harmony between ancient wisdom and sacred engineering. The Collective's ultimate extraction tool.",
	},
};
