export const worlds = [
	{
		id: 'training_shallows',
		name: 'L1: Training Shallows',
		summary: 'Mandatory orientation site. Low hazard, minimal profits.',
		description:
			'Entry-level asteroid cluster designated for new contractor orientation and basic extraction training. SpaceCo reminds you that survival during training is considered optional but encouraged.',
		transportRequirements: [],
		transportPrice: 35,
		size: 'small',
		shape: 'balanced',
		craters: {
			huge: [0, 0],
			big: [0, 0],
			medium: [1, 2],
			small: [3, 6],
			tiny: [2, 4],
		},
		caves: {
			huge: [0, 0],
			big: [0, 0],
			medium: [0, 1],
			small: [0, 1],
			tiny: [1, 5],
		},
		ground: {
			base: 'white',
			veins: [
				{
					color: 'orange',
					density: 9,
					size: 1.5,
					yield: 1.5,
					pattern: 'organic',
				},
				{
					color: 'black',
					density: 5,
					size: 1.2,
					yield: 3,
					pattern: 'scattered',
				},
				{
					color: 'white',
					density: 9,
					size: 3,
					yield: 1.2,
					pattern: 'radial',
				},
				{
					color: 'white',
					density: 2.2,
					size: 1.1,
					yield: 3.6,
					pattern: 'scattered',
				},
			],
		},
		tunnelSystems: {
			count: [2, 4],
			branchProbability: 0.6,
			maxBranches: 4,
			segmentLength: [7, 11],
			wanderStrength: 3,
		},
		lava_pools: {
			count: [0, 0],
		},
		gas_pockets: {
			count: [0, 0],
		},
		lava_bubbles: {
			count: [0, 0],
		},
		gas_bubbles: {
			count: [0, 0],
		},
		aliens: {
			budget: [0, 0],
		},
		items: {
			budget: [2, 5],
			types: ['oil'],
		},
		spaceco: {
			variant: 0,
			shop: {
				oil: [2, 3],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T2'],
			drills: ['T2'],
			engines: ['T2'],
			parts: [],
		},
		newPlayer: {
			credits: 0,
			items: {
				oil: 1,
			},
			configuration: {
				vehicle: 'T1',
				drill: 'T1',
				engine: 'T1',
			},
		},
		test: 'data',
	},
	{
		id: 'surface_prospects',
		name: 'L2: Surface Prospects',
		summary: 'Stable geology. Predictable yields. Barely dangerous.',
		description:
			'Shallow asteroid fields with reliable mineral deposits. Perfect for building operational experience. Your compliance with productivity targets is noted and appreciated.',
		transportRequirements: [['white', 120]],
		transportPrice: 105,
		size: 'small',
		shape: 'deep',
		craters: {
			huge: [1, 1],
			big: [0, 0],
			medium: [1, 3],
			small: [3, 6],
			tiny: [0, 0],
		},
		caves: {
			huge: [0, 0],
			big: [0, 0],
			medium: [1, 2],
			small: [0, 0],
			tiny: [4, 8],
		},
		ground: {
			base: 'orange',
			veins: [
				{
					color: 'orange',
					density: 15,
					size: 0.4,
					yield: 3,
					pattern: 'layered',
				},
				{
					color: 'white',
					density: 5,
					size: 1.4,
					yield: 2,
					pattern: 'organic',
				},
				{
					color: 'yellow',
					density: 2,
					size: 0.8,
					yield: 1.6,
					pattern: 'scattered',
				},
				{
					color: 'black',
					density: 1.5,
					size: 1.3,
					yield: 3.3,
					pattern: 'lightning',
				},
			],
		},
		tunnelSystems: {
			count: [2, 4],
			branchProbability: 0.3,
			maxBranches: 3,
			segmentLength: [4, 8],
			wanderStrength: 0.4,
		},
		lava_pools: {
			count: [2, 4],
		},
		lava_bubbles: {
			count: [3, 8],
		},
		gas_bubbles: {
			count: [0, 0],
		},
		aliens: {
			budget: [0, 2],
			types: {
				rock_mite: 70,
				hive_drone: 30,
			},
		},
		items: {
			budget: [3, 6],
			types: {
				oil: 70,
				repair_nanites: 30,
			},
		},
		spaceco: {
			variant: 0,
			shop: {
				oil: [2, 4],
				repair_nanites: [1, 2],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T3'],
			drills: ['T3'],
			engines: ['T3'],
			parts: ['T1'],
		},
		newPlayer: {
			credits: 200,
			items: {
				oil: 2,
				repair_nanites: 1,
			},
			configuration: {
				vehicle: 'T2',
				drill: 'T2',
				engine: 'T2',
			},
		},
		gas_pockets: {
			count: [0, 0],
		},
	},
	{
		id: 'amber_extraction_zone',
		name: 'L3: Amber Extraction Zone',
		summary: 'Rich pentrilium deposits. Moderate thermal activity detected.',
		description:
			'Mid-tier asteroid belt showing promising pentrilium concentrations and manageable heat signatures. First-degree burns remain within acceptable operational parameters.',
		transportRequirements: [['orange', 150]],
		transportPrice: 210,
		size: 'medium',
		shape: 'wide',
		craters: {
			huge: [1, 1],
			big: [1, 2],
			medium: [3, 6],
			small: [8, 12],
			tiny: [5, 10],
		},
		caves: {
			huge: [0, 1],
			big: [1, 2],
			medium: [2, 4],
			small: [4, 7],
			tiny: [3, 6],
		},
		ground: {
			base: 'yellow',
			veins: [
				{
					color: 'yellow',
					density: 18,
					size: 2.2,
					yield: 2.5,
					pattern: 'organic',
				},
				{
					color: 'orange',
					density: 1.1,
					size: 0.7,
					yield: 0,
					pattern: 'cellular',
				},
				{
					color: 'black',
					density: 2,
					size: 1.5,
					yield: 3.2,
					pattern: 'scattered',
				},
				{
					color: 'yellow',
					density: 4.5,
					size: 1.2,
					yield: 1.1,
					pattern: 'radial',
				},
				{
					color: 'yellow',
					density: 2,
					size: 1,
					yield: 4,
					pattern: 'scattered',
				},
			],
		},
		tunnelSystems: {
			count: [2, 4],
			branchProbability: 0.3,
			maxBranches: 3,
			segmentLength: [4, 8],
			wanderStrength: 0.4,
		},
		lava_pools: {
			count: [2, 3],
		},
		gas_pockets: {
			count: [1, 2],
		},
		lava_bubbles: {
			count: [5, 12],
		},
		gas_bubbles: {
			count: [3, 8],
		},
		aliens: {
			budget: [2, 4],
			types: {
				rock_mite: 50,
				hive_drone: 40,
				gift_bearer: 10,
			},
		},
		items: {
			budget: [1, 4],
			types: {
				oil: 60,
				repair_nanites: 25,
				spaceco_teleporter: 15,
			},
		},
		spaceco: {
			variant: 0,
			shop: {
				oil: [3, 5],
				repair_nanites: [2, 3],
				spaceco_teleporter: [1, 1],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T4'],
			drills: ['T4'],
			engines: ['T4'],
			parts: ['T1', 'T2'],
		},
		newPlayer: {
			credits: 500,
			items: {
				oil: 3,
				repair_nanites: 2,
			},
			configuration: {
				vehicle: 'T3',
				drill: 'T3',
				engine: 'T3',
			},
		},
	},
	{
		id: 'verdant_volatiles',
		name: 'L4: Verdant Volatiles',
		summary: 'Byzanium veins confirmed. Gas pockets complicate extraction.',
		description:
			'Byzanium-rich asteroid cluster with elevated instability readings. Proceed with standard caution protocols. Atmospheric toxicity falls within legally defensible exposure limits.',
		transportRequirements: [['yellow', 180]],
		transportPrice: 350,
		size: 'medium',
		shape: 'wide',
		craters: {
			huge: [2, 3],
			big: [2, 5],
			medium: [5, 9],
			small: [0, 0],
			tiny: [0, 0],
		},
		caves: {
			huge: [0, 1],
			big: [2, 4],
			medium: [3, 6],
			small: [4, 7],
			tiny: [4, 8],
		},
		ground: {
			base: 'green',
			veins: [
				{
					color: 'green',
					density: 3,
					size: 2,
					yield: 3.1,
					pattern: 'organic',
				},
				{
					color: 'teal',
					density: 3.2,
					size: 1.1,
					yield: 1.5,
					pattern: 'organic',
				},
				{
					color: 'yellow',
					density: 33,
					size: 0.3,
					yield: 3,
					pattern: 'percolation',
				},
				{
					color: 'green',
					density: 5,
					size: 1.1,
					yield: 2.1,
					pattern: 'fractal',
				},
			],
		},
		tunnelSystems: {
			count: [2, 4],
			branchProbability: 0.3,
			maxBranches: 3,
			segmentLength: [4, 8],
			wanderStrength: 0.4,
		},
		lava_pools: {
			count: [0, 0],
		},
		gas_pockets: {
			count: [2, 4],
		},
		lava_bubbles: {
			count: [5, 10],
		},
		gas_bubbles: {
			count: [9, 18],
		},
		aliens: {
			budget: [1, 4],
			types: {
				rock_mite: 25,
				hive_drone: 20,
				gas_sporecyst: 30,
				void_drifter: 20,
				gift_bearer: 5,
			},
		},
		items: {
			budget: [0, 3],
			types: {
				oil: 40,
				battery: 30,
				repair_nanites: 20,
				spaceco_teleporter: 10,
			},
		},
		spaceco: {
			variant: 0,
			shop: {
				oil: [2, 3],
				battery: [1, 2],
				repair_nanites: [1, 2],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: [0, 1],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T5'],
			drills: ['T5'],
			engines: ['T5'],
			parts: ['T2', 'T3'],
		},
		newPlayer: {
			credits: 400,
			items: {
				oil: 1,
				battery: 1,
				repair_nanites: 1,
			},
			configuration: {
				vehicle: 'T4',
				drill: 'T4',
				engine: 'T4',
			},
		},
	},
	{
		id: 'ethereal_depths',
		name: 'L5: Ethereal Depths',
		summary: 'Premium etherium concentration. Crushing depth recommended.',
		description:
			'Deep etherium deposits detected in stable geological formations. Excellent profit margins projected. Void exposure symptoms are temporary and covered under your contract.',
		transportRequirements: [['green', 220]],
		transportPrice: 525,
		size: 'small',
		shape: 'tall',
		craters: {
			huge: [0, 1],
			big: [2, 3],
			medium: [4, 8],
			small: [10, 16],
			tiny: [8, 14],
		},
		caves: {
			huge: [0, 0],
			big: [0, 0],
			medium: [0, 1],
			small: [3, 6],
			tiny: [4, 8],
		},
		ground: {
			base: 'teal',
			veins: [
				{
					color: 'teal',
					density: 20,
					size: 2,
					yield: 2.8,
					pattern: 'organic',
				},
				{
					color: 'blue',
					density: 10,
					size: 1.4,
					yield: 2.2,
					pattern: 'lightning',
				},
				{
					color: 'green',
					density: 2,
					size: 2,
					yield: 3.1,
					pattern: 'flow',
				},
				{
					color: 'teal',
					density: 2.6,
					size: 1,
					yield: 4,
					pattern: 'scattered',
				},
				{
					color: 'purple',
					density: 2,
					size: 1,
					yield: 1.5,
					pattern: 'layered',
				},
			],
		},
		tunnelSystems: {
			count: [0, 0],
			branchProbability: 0.3,
			maxBranches: 3,
			segmentLength: [4, 8],
			wanderStrength: 0.4,
		},
		lava_pools: {
			count: [1, 3],
		},
		gas_pockets: {
			count: [0, 0],
		},
		lava_bubbles: {
			count: [0, 0],
		},
		gas_bubbles: {
			count: [9, 22],
		},
		aliens: {
			budget: [2, 4],
			types: {
				rock_mite: 20,
				hive_drone: 15,
				gas_sporecyst: 25,
				void_drifter: 20,
				tunnel_chomper: 15,
				gift_bearer: 5,
			},
		},
		items: {
			budget: [0, 2],
			types: {
				oil: 25,
				battery: 40,
				repair_nanites: 20,
				spaceco_teleporter: 10,
				timed_charge: 5,
			},
		},
		spaceco: {
			variant: 0,
			shop: {
				oil: [2, 3],
				battery: [1, 2],
				repair_nanites: [1, 2],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: 1,
				timed_charge: [1, 2],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T6'],
			drills: ['T6'],
			engines: ['T6'],
			parts: ['T3', 'T4'],
		},
		newPlayer: {
			credits: 600,
			items: {
				battery: 1,
				repair_nanites: 1,
			},
			configuration: {
				vehicle: 'T5',
				drill: 'T5',
				engine: 'T5',
			},
		},
	},
	{
		id: 'azure_anomalies',
		name: 'L6: Azure Anomalies',
		summary: 'Mithril veins identified. Sensor glitches are normal.',
		description:
			'Mithril-bearing formations with unusual energy signatures. Geological surveys report minor sensor interference. Hallucinations and temporal displacement are not covered by insurance.',
		transportRequirements: [['teal', 260]],
		transportPrice: 770,
		size: 'small',
		shape: 'balanced',
		craters: {
			huge: [0, 0],
			big: [0, 0],
			medium: [6, 10],
			small: [14, 22],
			tiny: [10, 18],
		},
		caves: {
			huge: [0, 0],
			big: [0, 0],
			medium: [2, 4],
			small: [5, 8],
			tiny: [8, 14],
		},
		ground: {
			base: 'blue',
			veins: [
				{
					color: 'blue',
					density: 2.6,
					size: 2.2,
					yield: 4,
					pattern: 'organic',
				},
				{
					color: 'blue',
					density: 4.4,
					size: 1.6,
					yield: 3,
					pattern: 'noise_bands',
				},
				{
					color: 'purple',
					density: 1,
					size: 1.6,
					yield: 2.5,
					pattern: 'lightning',
				},
				{
					color: 'teal',
					density: 2,
					size: 1.2,
					yield: 2,
					pattern: 'fractal',
				},
				{
					color: 'pink',
					density: 2,
					size: 1.6,
					yield: 2.5,
					pattern: 'layered',
				},
			],
		},
		tunnelSystems: {
			count: [0, 0],
			branchProbability: 0.3,
			maxBranches: 3,
			segmentLength: [4, 8],
			wanderStrength: 0.4,
		},
		lava_pools: {
			count: [0, 0],
		},
		gas_pockets: {
			count: [2, 4],
		},
		lava_bubbles: {
			count: [0, 0],
		},
		gas_bubbles: {
			count: [0, 0],
		},
		aliens: {
			budget: [1, 3],
			types: {
				psykick_scout: 25,
				void_drifter: 20,
				tunnel_chomper: 15,
				hive_soldier: 15,
				depth_guardian: 15,
				earth_mover: 10,
			},
		},
		items: {
			budget: [0, 1],
			types: {
				battery: 50,
				super_oxygen_liquid_nitrogen: 20,
				repair_nanites: 15,
				timed_charge: 10,
				remote_charge: 5,
			},
		},
		spaceco: {
			variant: 1,
			shop: {
				battery: [2, 3],
				repair_nanites: [1, 2],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: 1,
				timed_charge: [1, 2],
				remote_charge: [0, 1],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T7'],
			drills: ['T7'],
			engines: ['T7'],
			parts: ['T4', 'T5'],
		},
		newPlayer: {
			credits: 750,
			items: {
				battery: 1,
				repair_nanites: 1,
			},
			configuration: {
				vehicle: 'T6',
				drill: 'T6',
				engine: 'T6',
			},
		},
	},
	{
		id: 'prismatic_confluence',
		name: 'L7: Prismatic Confluence',
		summary: 'Exceptional octanium yield. Ignore the screaming.',
		description:
			'High-grade octanium deposits in complex crystalline matrices. Extraction teams report "unusual acoustic phenomena." SpaceCo confirms sounds are geological in nature and not distress signals.',
		transportRequirements: [['blue', 300]],
		transportPrice: 1050,
		size: 'large',
		shape: 'wide',
		craters: {
			huge: [1, 2],
			big: [2, 4],
			medium: [8, 14],
			small: [16, 26],
			tiny: [12, 22],
		},
		caves: {
			huge: [0, 2],
			big: [1, 3],
			medium: [3, 8],
			small: [9, 15],
			tiny: [8, 13],
		},
		ground: {
			base: 'purple',
			veins: [
				{
					color: 'purple',
					density: 3,
					size: 3,
					yield: 3,
					pattern: 'organic',
				},
				{
					color: 'pink',
					density: 1,
					size: 2,
					yield: 2.8,
					pattern: 'lightning',
				},
				{
					color: 'blue',
					density: 3,
					size: 1.4,
					yield: 1.5,
					pattern: 'lightning',
				},
			],
		},
		tunnelSystems: {
			count: [4, 10],
			branchProbability: 1,
			maxBranches: 3,
			segmentLength: [3, 7],
			wanderStrength: 0.9,
		},
		lava_pools: {
			count: [3, 5],
		},
		gas_pockets: {
			count: [0, 0],
		},
		lava_bubbles: {
			count: [5, 15],
		},
		gas_bubbles: {
			count: [3, 8],
		},
		aliens: {
			budget: [3, 7],
			types: {
				mimic_ore: 25,
				psykick_scout: 20,
				hive_soldier: 20,
				tunnel_chomper: 15,
				void_drifter: 12,
				earth_mover: 8,
			},
		},
		items: {
			budget: [1, 3],
			types: {
				battery: 40,
				super_oxygen_liquid_nitrogen: 30,
				repair_nanites: 15,
				remote_charge: 10,
				spaceco_teleport_station: 5,
			},
		},
		spaceco: {
			variant: 1,
			shop: {
				battery: [2, 3],
				super_oxygen_liquid_nitrogen: [1, 1],
				repair_nanites: [1, 2],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: 1,
				remote_charge: 1,
				spaceco_teleport_station: [0, 1],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T8'],
			drills: ['T8'],
			engines: ['T8'],
			parts: ['T5', 'T6'],
		},
		newPlayer: {
			credits: 800,
			items: {
				battery: 1,
				super_oxygen_liquid_nitrogen: 1,
				repair_nanites: 1,
			},
			configuration: {
				vehicle: 'T7',
				drill: 'T7',
				engine: 'T7',
			},
		},
	},
	{
		id: 'resonant_caverns',
		name: 'L8: Resonant Caverns',
		summary: 'Dense saronite networks. Equipment failures are expected.',
		description:
			'Saronite veins embedded in acoustically active rock formations. Equipment malfunctions reported but profits remain strong. Your rig warranty was voided three levels ago.',
		transportRequirements: [['purple', 340]],
		transportPrice: 1400,
		size: 'large',
		shape: 'tall',
		craters: {
			huge: [1, 2],
			big: [1, 2],
			medium: [1, 2],
			small: [12, 20],
			tiny: [10, 16],
		},
		caves: {
			huge: [0, 1],
			big: [4, 7],
			medium: [4, 8],
			small: [14, 22],
			tiny: [12, 20],
		},
		ground: {
			base: 'pink',
			veins: [
				{
					color: 'pink',
					density: 4,
					size: 2.6,
					yield: 3,
					pattern: 'organic',
				},
				{
					color: 'red',
					density: 1,
					size: 2,
					yield: 3,
					pattern: 'lightning',
				},
				{
					color: 'purple',
					density: 3.4,
					size: 1.2,
					yield: 2.4,
					pattern: 'scattered',
				},
			],
		},
		tunnelSystems: {
			count: [10, 20],
			branchProbability: 0.6,
			maxBranches: 5,
			segmentLength: [9, 13],
			wanderStrength: 0.9,
		},
		lava_pools: {
			count: [0, 1],
		},
		gas_pockets: {
			count: [0, 1],
		},
		lava_bubbles: {
			count: [10, 20],
		},
		gas_bubbles: {
			count: [10, 20],
		},
		aliens: {
			budget: [2, 4],
			types: {
				psykick_warrior: 25,
				spawn_mother: 20,
				tunnel_chomper: 18,
				hive_soldier: 15,
				depth_guardian: 12,
				psykick_scout: 10,
			},
		},
		items: {
			budget: [0, 2],
			types: {
				battery: 30,
				super_oxygen_liquid_nitrogen: 40,
				repair_nanites: 20,
				gravity_charge: 10,
			},
		},
		spaceco: {
			variant: 1,
			shop: {
				battery: [1, 2],
				super_oxygen_liquid_nitrogen: [1, 2],
				repair_nanites: [1, 2],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: 1,
				remote_charge: [1, 2],
				spaceco_teleport_station: 1,
				gravity_charge: [0, 1],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T9'],
			drills: ['T9'],
			engines: ['T9'],
			parts: ['T6', 'T7'],
		},
		newPlayer: {
			credits: 1000,
			items: {
				super_oxygen_liquid_nitrogen: 1,
				repair_nanites: 1,
			},
			configuration: {
				vehicle: 'T8',
				drill: 'T8',
				engine: 'T8',
			},
		},
	},
	{
		id: 'crimson_foundries',
		name: 'L9: Crimson Foundries',
		summary: 'Peak adamantite concentrations. Radio silence is normal.',
		description:
			'Dense adamantite deposits in thermally unstable substrates. Communications with field teams increasingly irregular. Previous contractors are simply focused on their work.',
		transportRequirements: [['pink', 380]],
		transportPrice: 1890,
		size: 'medium',
		shape: 'balanced',
		craters: {
			huge: [1, 2],
			big: [2, 4],
			medium: [7, 12],
			small: [16, 26],
			tiny: [14, 24],
		},
		caves: {
			huge: [0, 0],
			big: [1, 3],
			medium: [5, 9],
			small: [6, 9],
			tiny: [14, 22],
		},
		ground: {
			base: 'red',
			veins: [
				{
					color: 'red',
					density: 40,
					size: 9,
					yield: 4,
					pattern: 'percolation',
				},
				{
					color: 'red',
					density: 4,
					size: 2,
					yield: 1.5,
					pattern: 'organic',
				},
				{
					color: 'pink',
					density: 2,
					size: 2.4,
					yield: 3.5,
					pattern: 'organic',
				},
			],
		},
		tunnelSystems: {
			count: [10, 20],
			branchProbability: 0.6,
			maxBranches: 5,
			segmentLength: [9, 13],
			wanderStrength: 0.9,
		},
		lava_pools: {
			count: [1, 2],
		},
		gas_pockets: {
			count: [1, 2],
		},
		lava_bubbles: {
			count: [12, 20],
		},
		gas_bubbles: {
			count: [10, 16],
		},
		aliens: {
			budget: [3, 5],
			types: {
				lava_spitter: 30,
				psykick_warrior: 20,
				tunnel_chomper: 18,
				spawn_mother: 15,
				hive_soldier: 10,
				depth_guardian: 7,
			},
		},
		items: {
			budget: [0, 4],
			types: {
				super_oxygen_liquid_nitrogen: 60,
				repair_nanites: 25,
				gravity_charge: 15,
			},
		},
		spaceco: {
			variant: 1,
			shop: {
				super_oxygen_liquid_nitrogen: [2, 3],
				repair_nanites: [1, 2],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: 1,
				remote_charge: [1, 2],
				spaceco_teleport_station: 1,
				gravity_charge: 1,
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T10'],
			drills: ['T10'],
			engines: ['T10'],
			parts: ['T7', 'T8'],
		},
		newPlayer: {
			credits: 1200,
			items: {
				super_oxygen_liquid_nitrogen: 2,
				repair_nanites: 1,
			},
			configuration: {
				vehicle: 'T9',
				drill: 'T9',
				engine: 'T9',
			},
		},
	},
	{
		id: 'obsidian_throne',
		name: 'L10: Obsidian Throne',
		summary: 'Ultimate quadium reserves. Questions are discouraged.',
		description:
			'Maximum-density quadium concentrations detected. All previous survey data has been reclassified. Proceed as directed. Survivors will be debriefed.',
		transportRequirements: [['red', 420]],
		transportPrice: 2450,
		size: 'large',
		shape: 'balanced',
		craters: {
			huge: [0, 0],
			big: [1, 1],
			medium: [8, 11],
			small: [16, 20],
			tiny: [16, 28],
		},
		caves: {
			huge: [1, 1],
			big: [1, 1],
			medium: [12, 20],
			small: [20, 32],
			tiny: [18, 30],
		},
		ground: {
			base: 'red',
			veins: [
				{
					color: 'red',
					density: 1,
					size: 4.4,
					yield: 3,
					pattern: 'flow',
				},
				{
					color: 'white',
					density: 2.5,
					size: 1.2,
					yield: 4,
					pattern: 'organic',
				},
				{
					color: 'black',
					density: 1,
					size: 1.1,
					yield: 4,
					pattern: 'organic',
				},
			],
		},
		tunnelSystems: {
			count: [4, 7],
			branchProbability: 0.3,
			maxBranches: 3,
			segmentLength: [4, 8],
			wanderStrength: 0.4,
		},
		lava_pools: {
			count: [3, 8],
		},
		gas_pockets: {
			count: [2, 6],
		},
		lava_bubbles: {
			count: [15, 25],
		},
		gas_bubbles: {
			count: [12, 20],
		},
		aliens: {
			budget: [3, 8],
			types: {
				psykick_warrior: 20,
				depth_guardian: 18,
				spawn_mother: 15,
				lava_spitter: 15,
				mimic_ore: 12,
				hive_soldier: 10,
				tunnel_chomper: 10,
			},
		},
		items: {
			budget: [0, 1],
			types: {
				super_oxygen_liquid_nitrogen: 50,
				repair_nanites: 30,
				gravity_charge: 15,
				void_implosion: 5,
			},
		},
		spaceco: {
			variant: 2,
			shop: {
				super_oxygen_liquid_nitrogen: [2, 3],
				repair_nanites: [1, 2],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: [1, 2],
				remote_charge: [1, 2],
				spaceco_teleport_station: 1,
				gravity_charge: [1, 2],
				void_implosion: [0, 1],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T11'],
			drills: ['T11'],
			engines: ['T11'],
			parts: ['T8', 'T9'],
		},
		newPlayer: {
			credits: 1500,
			items: {
				super_oxygen_liquid_nitrogen: 2,
				repair_nanites: 2,
			},
			configuration: {
				vehicle: 'T10',
				drill: 'T10',
				engine: 'T10',
			},
		},
	},
	{
		id: 'sacred_fragments',
		name: 'L11: Sacred Fragments',
		summary: 'Priority quantum minerals. The Collective is watching.',
		description:
			'High-value quantum-resonant mineral deposits identified. Recovery of these specimens is of utmost priority to the Collective. Your contribution will be remembered.',
		transportRequirements: [['black', 500]],
		transportPrice: 4900,
		size: 'huge',
		shape: 'tall',
		craters: {
			huge: [1, 2],
			big: [1, 2],
			medium: [8, 14],
			small: [16, 20],
			tiny: [16, 26],
		},
		caves: {
			huge: [1, 2],
			big: [1, 2],
			medium: [12, 18],
			small: [18, 28],
			tiny: [16, 26],
		},
		ground: {
			base: 'black',
			veins: [
				{
					color: 'red',
					density: 4,
					size: 1.6,
					yield: 2.8,
					pattern: 'scattered',
				},
				{
					color: 'black',
					density: 2,
					size: 1.1,
					yield: 2.3,
					pattern: 'organic',
				},
			],
		},
		tunnelSystems: {
			count: [10, 10],
			branchProbability: 0.5,
			maxBranches: 5,
			segmentLength: [5, 10],
			wanderStrength: 0.5,
		},
		lava_pools: {
			count: [3, 7],
		},
		gas_pockets: {
			count: [3, 7],
		},
		lava_bubbles: {
			count: [18, 28],
		},
		gas_bubbles: {
			count: [15, 24],
		},
		aliens: {
			budget: [6, 12],
			types: {
				psykick_warrior: 20,
				depth_guardian: 18,
				spawn_mother: 15,
				mimic_ore: 12,
				lava_spitter: 12,
				gas_sporecyst: 12,
				hive_soldier: 11,
			},
		},
		items: {
			budget: [0, 1],
			types: {
				super_oxygen_liquid_nitrogen: 40,
				psykick_egg: 30,
				repair_nanites: 20,
				void_implosion: 10,
			},
		},
		spaceco: {
			variant: 2,
			shop: {
				super_oxygen_liquid_nitrogen: [2, 4],
				repair_nanites: [2, 3],
				spaceco_teleporter: [1, 2],
				advanced_teleporter: [1, 2],
				remote_charge: [1, 2],
				spaceco_teleport_station: 1,
				gravity_charge: [1, 2],
				void_implosion: 1,
				transport_insurance: [3, 5],
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T12'],
			drills: ['T12'],
			engines: ['T12'],
			parts: ['T9', 'T10'],
		},
		newPlayer: {
			credits: 1800,
			items: {
				super_oxygen_liquid_nitrogen: 3,
				repair_nanites: 2,
			},
			configuration: {
				vehicle: 'T11',
				drill: 'T11',
				engine: 'T11',
			},
		},
	},
	{
		id: 'fractured_prospects_b',
		name: 'L3B: Fractured Prospects',
		summary: 'Backup site. Unstable but profitable for experienced miners.',
		description:
			'Secondary extraction site with elevated instability markers. Designated as backup operations zone. Previous incidents have been thoroughly investigated and blamed on contractor error.',
		transportRequirements: [
			['orange', 165],
			['xp', 3750],
		],
		transportPrice: 350,
		size: 'large',
		shape: 'wide',
		craters: {
			huge: [0, 1],
			big: [0, 1],
			medium: [5, 10],
			small: [5, 10],
			tiny: [5, 10],
		},
		caves: {
			huge: [0, 1],
			big: [0, 1],
			medium: [5, 10],
			small: [5, 10],
			tiny: [5, 10],
		},
		ground: {
			base: 'yellow',
			veins: [
				{
					color: 'black',
					density: 1.1,
					size: 1.1,
					yield: 1.1,
					pattern: 'maze',
				},
				{
					color: 'black',
					density: 1.9,
					size: 1.8,
					yield: 3,
					pattern: 'scattered',
				},
				{
					color: 'yellow',
					density: 2,
					size: 1.8,
					yield: 4,
					pattern: 'scattered',
				},
			],
		},
		tunnelSystems: {
			count: [10, 10],
			branchProbability: 0.5,
			maxBranches: 5,
			segmentLength: [5, 10],
			wanderStrength: 0.5,
		},
		lava_pools: {
			count: [4, 8],
		},
		gas_pockets: {
			count: [3, 6],
		},
		lava_bubbles: {
			count: [20, 30],
		},
		gas_bubbles: {
			count: [18, 26],
		},
		aliens: {
			budget: [2, 5],
			types: {
				rock_mite: 30,
				hive_drone: 25,
				gas_sporecyst: 20,
				void_drifter: 15,
				gift_bearer: 10,
			},
		},
		items: {
			budget: [3, 5],
			types: {
				oil: 40,
				repair_nanites: 35,
				spaceco_teleporter: 20,
				timed_charge: 5,
			},
		},
		spaceco: {
			variant: 2,
			shop: {
				oil: [4, 6],
				repair_nanites: [2, 4],
				spaceco_teleporter: [2, 3],
				timed_charge: [1, 2],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T4'],
			parts: ['T2', 'T3'],
		},
		newPlayer: {
			credits: 650,
			items: {
				oil: 2,
				repair_nanites: 2,
			},
			configuration: {
				vehicle: 'T3',
				drill: 'T3',
				engine: 'T3',
			},
		},
	},
	{
		id: 'unstable_confluence_b',
		name: 'L7B: Unstable Confluence',
		summary: 'Advanced octanium site. High risk, higher rewards.',
		description:
			'Volatile secondary site with irregular crystalline formations. Mining operations proceed at contractor discretion. SpaceCo Legal has pre-approved all liability waivers.',
		transportRequirements: [
			['blue', 330],
			['xp', 12000],
		],
		transportPrice: 1260,
		size: 'huge',
		shape: 'balanced',
		craters: {
			huge: [1, 2],
			big: [2, 4],
			medium: [5, 8],
			small: [12, 20],
			tiny: [10, 16],
		},
		caves: {
			huge: [1, 2],
			big: [2, 3],
			medium: [6, 10],
			small: [12, 18],
			tiny: [10, 16],
		},
		ground: {
			base: 'purple',
			veins: [
				{
					color: 'purple',
					density: 20,
					size: 2.2,
					yield: 3,
					pattern: 'organic',
				},
				{
					color: 'pink',
					density: 1.8,
					size: 1.8,
					yield: 2.5,
					pattern: 'lightning',
				},
				{
					color: 'blue',
					density: 9,
					size: 6,
					yield: 2.7,
					pattern: 'percolation',
				},
			],
		},
		tunnelSystems: {
			count: [10, 10],
			branchProbability: 0.5,
			maxBranches: 5,
			segmentLength: [5, 10],
			wanderStrength: 0.5,
		},
		lava_pools: {
			count: [4, 6],
		},
		gas_pockets: {
			count: [4, 6],
		},
		lava_bubbles: {
			count: [25, 35],
		},
		gas_bubbles: {
			count: [20, 30],
		},
		aliens: {
			budget: [3, 9],
			types: {
				psykick_scout: 25,
				hive_soldier: 20,
				void_drifter: 18,
				tunnel_chomper: 15,
				mimic_ore: 12,
				earth_mover: 10,
			},
		},
		items: {
			budget: [2, 7],
			types: {
				battery: 30,
				super_oxygen_liquid_nitrogen: 35,
				repair_nanites: 20,
				remote_charge: 10,
				advanced_teleporter: 5,
			},
		},
		spaceco: {
			variant: 0,
			shop: {
				battery: [3, 5],
				super_oxygen_liquid_nitrogen: [2, 3],
				repair_nanites: [2, 4],
				spaceco_teleporter: [2, 3],
				advanced_teleporter: [1, 2],
				remote_charge: [2, 3],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			engines: ['T8'],
			parts: ['T6', 'T7'],
		},
		newPlayer: {
			credits: 1750,
			items: {
				battery: 2,
				super_oxygen_liquid_nitrogen: 1,
				repair_nanites: 2,
			},
			configuration: {
				vehicle: 'T7',
				drill: 'T7',
				engine: 'T7',
			},
		},
	},
	{
		id: 'thermal_breach_b',
		name: 'L9B: Thermal Breach',
		summary: 'Extreme adamantite yields. Survival optional, profits mandatory.',
		description:
			'High-temperature secondary site with extreme geological instability. Operations authorized despite elevated risk profile. Your next of kin have been notified of potential outcomes.',
		transportRequirements: [
			['pink', 418],
			['xp', 22500],
		],
		transportPrice: 2240,
		size: 'large',
		shape: 'tall',
		craters: {
			huge: [2, 3],
			big: [3, 5],
			medium: [6, 10],
			small: [14, 22],
			tiny: [12, 20],
		},
		caves: {
			huge: [3, 5],
			big: [5, 8],
			medium: [10, 15],
			small: [16, 24],
			tiny: [14, 22],
		},
		ground: {
			base: 'red',
			veins: [
				{
					color: 'red',
					density: 28,
					size: 2.6,
					yield: 3.6,
					pattern: 'organic',
				},
				{
					color: 'pink',
					density: 6,
					size: 1.4,
					yield: 4,
					pattern: 'fractal',
				},
			],
		},
		tunnelSystems: {
			count: [10, 10],
			branchProbability: 0.5,
			maxBranches: 5,
			segmentLength: [5, 10],
			wanderStrength: 0.5,
		},
		lava_pools: {
			count: [3, 5],
		},
		gas_pockets: {
			count: [2, 4],
		},
		lava_bubbles: {
			count: [30, 40],
		},
		gas_bubbles: {
			count: [25, 35],
		},
		aliens: {
			budget: [4, 8],
			types: {
				lava_spitter: 30,
				psykick_warrior: 22,
				tunnel_chomper: 18,
				hive_soldier: 15,
				spawn_mother: 10,
				depth_guardian: 5,
			},
		},
		items: {
			budget: [1, 3],
			types: {
				super_oxygen_liquid_nitrogen: 50,
				repair_nanites: 30,
				gravity_charge: 15,
				remote_charge: 5,
			},
		},
		spaceco: {
			variant: 1,
			shop: {
				super_oxygen_liquid_nitrogen: [4, 6],
				repair_nanites: [3, 5],
				spaceco_teleporter: [2, 4],
				advanced_teleporter: [2, 3],
				remote_charge: [2, 4],
				spaceco_teleport_station: [1, 2],
				gravity_charge: [1, 2],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T10'],
			drills: ['T10'],
			parts: ['T8', 'T9'],
		},
		newPlayer: {
			credits: 2750,
			items: {
				super_oxygen_liquid_nitrogen: 3,
				repair_nanites: 2,
			},
			configuration: {
				vehicle: 'T9',
				drill: 'T9',
				engine: 'T9',
			},
		},
	},
	{
		id: 'resonance_chamber_b',
		name: 'L11B: Resonance Chamber',
		summary: 'Quantum specimen recovery. The Collective requires perfection.',
		description:
			'Secondary quantum-mineral site with elevated harmonic signatures. Priority recovery operations for specialized specimens. Failure to deliver will result in contract renegotiation.',
		transportRequirements: [
			['black', 550],
			['xp', 45000],
		],
		transportPrice: 4200,
		size: 'large',
		shape: 'balanced',
		craters: {
			huge: [2, 3],
			big: [3, 6],
			medium: [10, 16],
			small: [20, 32],
			tiny: [18, 30],
		},
		caves: {
			huge: [0, 1],
			big: [3, 5],
			medium: [12, 18],
			small: [18, 28],
			tiny: [16, 26],
		},
		ground: {
			base: 'black',
			veins: [
				{
					color: 'purple',
					density: 1,
					size: 1,
					yield: 4.5,
					pattern: 'spiral',
				},
				{
					color: 'black',
					density: 2.2,
					size: 1.5,
					yield: 2.3,
					pattern: 'scattered',
				},
				{
					color: 'white',
					density: 3.1,
					size: 1,
					yield: 4,
					pattern: 'percolation',
				},
			],
		},
		tunnelSystems: {
			count: [10, 10],
			branchProbability: 0.5,
			maxBranches: 5,
			segmentLength: [10, 10],
			wanderStrength: 0.5,
		},
		lava_pools: {
			count: [8, 14],
		},
		gas_pockets: {
			count: [12, 20],
		},
		lava_bubbles: {
			count: [30, 40],
		},
		gas_bubbles: {
			count: [25, 35],
		},
		aliens: {
			budget: [4, 12],
			types: {
				psykick_warrior: 22,
				depth_guardian: 20,
				spawn_mother: 18,
				mimic_ore: 15,
				gas_sporecyst: 15,
				hive_soldier: 10,
			},
		},
		items: {
			budget: [1, 2],
			types: {
				super_oxygen_liquid_nitrogen: 35,
				psykick_egg: 40,
				repair_nanites: 20,
				void_implosion: 5,
			},
		},
		spaceco: {
			variant: 2,
			shop: {
				super_oxygen_liquid_nitrogen: [4, 7],
				repair_nanites: [3, 5],
				spaceco_teleporter: [3, 5],
				advanced_teleporter: [2, 4],
				remote_charge: [2, 4],
				spaceco_teleport_station: [2, 3],
				gravity_charge: [3, 5],
				void_implosion: [2, 3],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T13'],
			drills: ['T12', 'T13'],
			engines: ['T12'],
			parts: ['T11', 'T12'],
		},
		newPlayer: {
			credits: 4000,
			items: {
				super_oxygen_liquid_nitrogen: 4,
				repair_nanites: 3,
			},
			configuration: {
				vehicle: 'T11',
				drill: 'T11',
				engine: 'T11',
			},
		},
	},
	{
		id: 'void_sanctum_c',
		name: 'L11C: Void Sanctum',
		summary: 'Final collection zone. No backup contractors available.',
		description:
			'Tertiary quantum-mineral extraction zone with maximum resonance density. The Collective requires complete specimen recovery. This is your last assignment.',
		transportRequirements: [
			['black', 625],
			['xp', 20000],
		],
		transportPrice: 4900,
		size: 'medium',
		shape: 'tall',
		craters: {
			huge: [1, 2],
			big: [2, 5],
			medium: [8, 14],
			small: [18, 30],
			tiny: [16, 26],
		},
		caves: {
			huge: [1, 2],
			big: [2, 4],
			medium: [12, 18],
			small: [20, 32],
			tiny: [18, 28],
		},
		ground: {
			base: 'black',
			veins: [
				{
					color: 'white',
					density: 6,
					size: 1.4,
					yield: 3.4,
					pattern: 'fractal',
				},
				{
					color: 'orange',
					density: 2,
					size: 1,
					yield: 4,
					pattern: 'scattered',
				},
				{
					color: 'black',
					density: 2,
					size: 0.4,
					yield: 3,
					pattern: 'concentric',
				},
			],
		},
		tunnelSystems: {
			count: [10, 10],
			branchProbability: 0.5,
			maxBranches: 5,
			segmentLength: [10, 10],
			wanderStrength: 0.5,
		},
		lava_pools: {
			count: [0, 0],
		},
		gas_pockets: {
			count: [4, 6],
		},
		lava_bubbles: {
			count: [0, 0],
		},
		gas_bubbles: {
			count: [25, 35],
		},
		aliens: {
			budget: [4, 12],
			types: {
				rock_mite: 3,
				hive_drone: 3,
				psykick_scout: 3,
				tunnel_chomper: 8,
				void_drifter: 10,
				hive_soldier: 15,
				lava_spitter: 15,
				gas_sporecyst: 15,
				psykick_warrior: 15,
				depth_guardian: 8,
				mimic_ore: 5,
			},
		},
		items: {
			budget: [1, 2],
			types: {
				super_oxygen_liquid_nitrogen: 30,
				psykick_egg: 50,
				repair_nanites: 15,
				void_implosion: 5,
			},
		},
		spaceco: {
			variant: 2,
			shop: {
				super_oxygen_liquid_nitrogen: [4, 8],
				repair_nanites: [4, 6],
				spaceco_teleporter: [3, 6],
				advanced_teleporter: [3, 5],
				remote_charge: [3, 5],
				spaceco_teleport_station: [2, 4],
				gravity_charge: [3, 6],
				void_implosion: [2, 4],
				transport_insurance: 1,
				pension_credit_buyup: [0, 1],
			},
			vehicles: ['T14'],
			drills: ['T13'],
			engines: ['T12'],
			parts: ['T13', 'T14', 'T15', 'T16'],
		},
		newPlayer: {
			credits: 4500,
			items: {
				super_oxygen_liquid_nitrogen: 5,
				repair_nanites: 4,
			},
			configuration: {
				vehicle: 'T12',
				drill: 'T11',
				engine: 'T11',
			},
		},
	},
];
